camel-jboss
~~~~~~~~~~~

*Available as of Camel 2.1*

The link:camel-jboss.html[camel-jboss] is a component which allows you
to run Camel inside JBoss Application Server. This component is needed
due JBoss classloading challenges. +
 The component is a specialized Camel
link:pluggable-class-resolvers.html[Pluggable Class Resolvers] to remedy
this.

*JBoss version*

If you are using JBoss 4.x/5.x then you need to use `camel-jboss` JAR.
If you are using JBoss 6.x then you need to use `camel-jboss6` JAR.

The resolver is provided in the class
`org.apacheextras.camel.jboss.JBossPackageScanClassResolver` in the
`camel-jboss` jar file.

*Camel 2.8 onwards*

From *Camel 2.8* onwards there is no longer the need for using this
link:camel-jboss.html[camel-jboss] component as Camel is now capable of
loading type converters without package scanning. This requires though
that all 3rd party components with type converter must define the name
of the converter classes as FQN in the
`META-INF/org/apache/camel/TypeConverter` file. See more details at
link:type-converter.html[Type Converter]. +
 One exception is if you are using link:bindy.html[Bindy] component as
it still needs this JBoss resolver.

Using with Java DSL
^^^^^^^^^^^^^^^^^^^

You need to configure the resolver on the
link:camelcontext.html[CamelContext] which is done like this:

[source,java]
-------------------------------------------------------------------------------
  PackageScanClassResolver jbossResolver = new JBossPackageScanClassResolver();

  CamelContext context = new DefaultCamelContext();
  context.setPackageScanClassResolver(jbossResolver);
-------------------------------------------------------------------------------

Using with Spring XML
^^^^^^^^^^^^^^^^^^^^^

When using Spring XML its just a matter of defining a spring bean with
the JBoss class resolver as shown:

[source,java]
------------------------------------------------------------------------------------------------
   <bean id="jbossResolver" class="org.apacheextras.camel.jboss.JBossPackageScanClassResolver"/>

  <camelContext id="camel" xmlns="http://camel.apache.org/schema/spring">
    <route>
      <from uri="seda:start"/>
      <to uri="mock:result"/>
    </route>
  </camelContext>
------------------------------------------------------------------------------------------------

The http://camel-extra.googlecode.com/[Camel Extra] project was moved to
an official associated Apache site and as part of the migration the
package names in the source code must not use `org.apache` so we renamed
the packages as shown above. But _if you are using the *older* versions
of the JAR files_ then you need to use as shown below:

[source,java]
------------------------------------------------------------------------------------------
   <bean id="jbossResolver" class="org.apache.camel.jboss.JBossPackageScanClassResolver"/>
------------------------------------------------------------------------------------------

Dependencies
^^^^^^^^^^^^

You need to get the component from the
http://camel-extra.googlecode.com/[Camel Extra] project as JBoss uses
*LPGL* license which cannot be hosted at Apache.
