Db4o Component
~~~~~~~~~~~~~~

*Available as of Camel 2.5*

The *db4o:* component allows you to work with http://www.db4o.com[db4o]
NoSQL database. The camel-db4o library is provided by the
http://code.google.com/p/camel-extra/[Camel Extra] project which hosts
all *GPL related components for Camel.

Sending to the endpoint
^^^^^^^^^^^^^^^^^^^^^^^

Sending POJO object to the db4o endpoint adds and saves object into the
database. The body of the message is assumed to be a POJO that has to be
saved into the db40 database store.

Consuming from the endpoint
^^^^^^^^^^^^^^^^^^^^^^^^^^^

Consuming messages removes (or updates) POJO objects in the database.
This allows you to use a Db4o datastore as a logical queue; consumers
take messages from the queue and then delete them to logically remove
them from the queue.

If you do not wish to delete the object when it has been processed, you
can specify `consumeDelete=false` on the URI. This will result in the
POJO being processed each poll.

URI format
^^^^^^^^^^

[source,java]
------------------------
db4o:className[?options]
------------------------

You can append query options to the URI in the following format,
`?option=value&option=value&...`

Options
^^^^^^^

Name

Default Value

Description

`consumeDelete`

`true`

Option for `Db4oConsumer` only. Specifies whether or not the entity is
deleted after it is consumed.

`consumer.delay`

`500`

Option for consumer only. Delay in millis between each poll.

`consumer.initialDelay`

`1000`

Option for consumer only. Millis before polling starts.

`consumer.userFixedDelay`

`false`

Option for consumer only. Set to `true` to use fixed delay between
polls, otherwise fixed rate is used. See
http://java.sun.com/j2se/1.5.0/docs/api/java/util/concurrent/ScheduledExecutorService.html[ScheduledExecutorService]
in JDK for details.

See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

